import StyleDictionary from "style-dictionary";

/**
 * Custom format for CSS custom properties with theme structure
 * This generates CSS variables that match the existing structure in global.css
 */
StyleDictionary.registerFormat({
  name: "css/themed-variables",
  format: ({ dictionary }) => {
    const lightColors = [];
    const darkColors = [];
    const rootVars = [];

    dictionary.allTokens.forEach(token => {
      const name = token.path.join("-");

      if (token.path[0] === "color") {
        // Handle light/dark color tokens
        if (token.path[1] === "light") {
          const varName = `--${token.path.slice(2).join("-")}-color-light`;
          lightColors.push(`  ${varName}: ${token.value};`);
        } else if (token.path[1] === "dark") {
          const varName = `--${token.path.slice(2).join("-")}-color-dark`;
          darkColors.push(`  ${varName}: ${token.value};`);
        }
      } else {
        // Handle non-color tokens (spacing, radius, shadows, motion, typography)
        const varName = `--${name}`;
        rootVars.push(`  ${varName}: ${token.value};`);
      }
    });

    // Build the CSS output
    let css = "/** Design tokens generated by Style Dictionary */\n\n";
    css += ":root {\n";

    // Add light theme colors
    if (lightColors.length > 0) {
      css += "  /* Light theme colors */\n";
      css += `${lightColors.join("\n")}\n\n`;
    }

    // Add dark theme colors
    if (darkColors.length > 0) {
      css += "  /* Dark theme colors */\n";
      css += `${darkColors.join("\n")}\n\n`;
    }

    // Add default color references (pointing to light)
    css += "  /* Default to light values */\n";
    css += "  --primary-color: var(--primary-color-light);\n";
    css += "  --secondary-color: var(--secondary-color-light);\n";
    css += "  --remark-color: var(--remark-color-light);\n";
    css += "  --weak-color: var(--weak-color-light);\n";
    css += "  --background-color: var(--background-color-light);\n";
    css += "  --block-color: var(--block-color-light);\n";
    css += "  --shadow-color: var(--shadow-color-light);\n";
    css += "  --selection-color: var(--selection-color-light);\n";

    // Add other tokens
    if (rootVars.length > 0) {
      css += "\n  /* Other design tokens */\n";
      css += `${rootVars.join("\n")}\n`;
    }

    css += "}\n\n";

    // Add dark theme media query
    css += "/* Dark theme colors */\n";
    css += "@media (prefers-color-scheme: dark) {\n";
    css += "  :root {\n";
    css += "    /* Switch the tokens to reference the dark source values */\n";
    css += "    --primary-color: var(--primary-color-dark);\n";
    css += "    --secondary-color: var(--secondary-color-dark);\n";
    css += "    --remark-color: var(--remark-color-dark);\n";
    css += "    --weak-color: var(--weak-color-dark);\n";
    css += "    --background-color: var(--background-color-dark);\n";
    css += "    --block-color: var(--block-color-dark);\n";
    css += "    --shadow-color: var(--shadow-color-dark);\n";
    css += "    --selection-color: var(--selection-color-dark);\n";
    css += "  }\n";
    css += "}\n\n";

    // Add manual theme overrides
    css += "/* Manual theme overrides */\n";
    css += '[data-theme="light"] {\n';
    css += "  --primary-color: var(--primary-color-light);\n";
    css += "  --secondary-color: var(--secondary-color-light);\n";
    css += "  --remark-color: var(--remark-color-light);\n";
    css += "  --weak-color: var(--weak-color-light);\n";
    css += "  --background-color: var(--background-color-light);\n";
    css += "  --block-color: var(--block-color-light);\n";
    css += "  --shadow-color: var(--shadow-color-light);\n";
    css += "  --selection-color: var(--selection-color-light);\n";
    css += "}\n\n";
    css += '[data-theme="dark"] {\n';
    css += "  --primary-color: var(--primary-color-dark);\n";
    css += "  --secondary-color: var(--secondary-color-dark);\n";
    css += "  --remark-color: var(--remark-color-dark);\n";
    css += "  --weak-color: var(--weak-color-dark);\n";
    css += "  --background-color: var(--background-color-dark);\n";
    css += "  --block-color: var(--block-color-dark);\n";
    css += "  --shadow-color: var(--shadow-color-dark);\n";
    css += "  --selection-color: var(--selection-color-dark);\n";
    css += "}\n";

    return css;
  }
});

const config = {
  source: ["src/tokens/**/*.json", "!src/tokens/index.json"],
  platforms: {
    css: {
      transformGroup: "css",
      buildPath: "src/styles/",
      files: [
        {
          destination: "tokens.css",
          format: "css/themed-variables"
        }
      ]
    }
  }
};

export default config;
