import StyleDictionary from "style-dictionary";

/**
 * Custom format for CSS custom properties with theme structure
 * This generates CSS variables that match the existing structure in global.css
 */
StyleDictionary.registerFormat({
  name: "css/themed-variables",
  format: ({ dictionary }) => {
    const lightColors = [];
    const darkColors = [];
    const rootVars = [];

    // Extract color names dynamically from tokens
    const colorNames = new Set();

    dictionary.allTokens.forEach(token => {
      const name = token.path.join("-");

      if (token.path[0] === "color") {
        // Handle light/dark color tokens
        if (token.path[1] === "light") {
          const varName = `--${token.path.slice(2).join("-")}-color-light`;
          lightColors.push(`  ${varName}: ${token.value};`);
          // Track color names for later use
          colorNames.add(token.path.slice(2).join("-"));
        } else if (token.path[1] === "dark") {
          const varName = `--${token.path.slice(2).join("-")}-color-dark`;
          darkColors.push(`  ${varName}: ${token.value};`);
        }
      } else {
        // Handle non-color tokens (spacing, radius, shadows, motion, typography)
        const varName = `--${name}`;
        rootVars.push(`  ${varName}: ${token.value};`);
      }
    });

    // Helper function to generate color variable assignments
    const generateColorAssignments = (suffix, indent = "  ") => {
      return Array.from(colorNames)
        .map(name => `${indent}--${name}-color: var(--${name}-color-${suffix});`)
        .join("\n");
    };

    // Build the CSS output
    let css = "/** Design tokens generated by Style Dictionary */\n\n";
    css += ":root {\n";

    // Add light theme colors
    if (lightColors.length > 0) {
      css += "  /* Light theme colors */\n";
      css += `${lightColors.join("\n")}\n\n`;
    }

    // Add dark theme colors
    if (darkColors.length > 0) {
      css += "  /* Dark theme colors */\n";
      css += `${darkColors.join("\n")}\n\n`;
    }

    // Add default color references (pointing to light)
    css += "  /* Default to light values */\n";
    css += `${generateColorAssignments("light")}\n`;

    // Add other tokens
    if (rootVars.length > 0) {
      css += "\n  /* Other design tokens */\n";
      css += `${rootVars.join("\n")}\n`;
    }

    css += "}\n\n";

    // Add dark theme media query
    css += "/* Dark theme colors */\n";
    css += "@media (prefers-color-scheme: dark) {\n";
    css += "  :root {\n";
    css += "    /* Switch the tokens to reference the dark source values */\n";
    css += `${generateColorAssignments("dark", "    ")}\n`;
    css += "  }\n";
    css += "}\n\n";

    // Add manual theme overrides
    css += "/* Manual theme overrides */\n";
    css += '[data-theme="light"] {\n';
    css += `${generateColorAssignments("light")}\n`;
    css += "}\n\n";
    css += '[data-theme="dark"] {\n';
    css += `${generateColorAssignments("dark")}\n`;
    css += "}\n";

    return css;
  }
});

const config = {
  source: ["src/tokens/**/*.json", "!src/tokens/index.json"],
  platforms: {
    css: {
      transformGroup: "css",
      buildPath: "src/styles/",
      files: [
        {
          destination: "tokens.css",
          format: "css/themed-variables"
        }
      ]
    }
  }
};

export default config;
